/*
 * font.h -- glyph lookup for the terminal (pure, host-tested).
 *
 * Font data lives in font_ascii_data.h (generated by tools/romfont.py from
 * the TT3000 ROM) and font_graph_data.h (generated by tools/genfont.py). The
 * lookup function font_glyph(ch) returns a pointer to 8 bytes representing
 * the glyph rows in scanline order (bit 7 = leftmost pixel, ZX/Timex byte
 * order); the ASCII cell is 6 px wide within an 8-row glyph.
 *
 * Character mapping:
 * - ASCII 0x20-0x7E -> FONT_ASCII[ch - 0x20]
 * - Graphics codes 0xDF-0xFE (i.e. 0x5F-0x7E | 0x80) -> FONT_GRAPH[(ch & 0x7F) - 0x5F]
 * - Anything else -> blank glyph (space)
 *
 * The high-bit page (0x80-0xFE) is used by vtparse for DEC line-drawing:
 * ESC(0 designates G0 as special graphics; bytes 0x5F-0x7E become cell codes
 * 0xDF-0xFE (b | 0x80). This keeps the cell model simple: {ch, attr} where ch
 * is just the byte to render, and the font lookup handles the mapping.
 *
 * Per the toolchain rule, no z80.h here: this is pure logic compiled on both
 * host (native cc) and target (z88dk/SDCC).
 */
#ifndef FONT_H
#define FONT_H

#include "types.h"

/*
 * Return a pointer to 8 glyph row bytes for the given character code.
 * The returned pointer is valid for the lifetime of the program (static data).
 * Invalid codes (outside ASCII and graphics ranges) return a blank glyph.
 */
const u8 *font_glyph(u8 ch);

#endif /* FONT_H */
