#!/usr/bin/env python3
"""
genfont.py -- author the terminal's DEC special-graphics glyphs as pixel art,
emit C data.

Run:  python3 tools/genfont.py > src/font_graph_data.h

The ASCII font comes from the TT3000 ROM instead (see tools/romfont.py and
src/font_ascii_data.h); this script only authors FONT_GRAPH.

Each glyph is 8 rows of up to 6 columns. '#' = ink pixel, anything else =
blank. Bit 7 (0x80) is the LEFTMOST pixel (standard ZX/Timex scanline byte
order), so the renderer can copy a row byte straight to the hi-res display
file; a 6-px cell occupies bits 7..2 and leaves bits 1..0 unused.

Table: FONT_GRAPH[0x5F..0x7E][8]. vtparse maps a graphics byte b to cell code
(b|0x80); font.c looks up FONT_GRAPH[(code & 0x7F) - 0x5F]. Box-drawing
glyphs put the vertical run in column 2 and the horizontal run across all six
columns, so lines connect across cells (spec §8).
"""

# DEC Special Graphics on a 6-px cell (bits 7..2). The line-drawing glyphs use
# the VT-100 letters: j/k/l/m corners, q horizontal, x vertical, n/t/u/v/w joins.
# The vertical run sits in column 2 and the horizontal run spans all six columns,
# so runs meet across cell boundaries and the half-lines OR back to a full run.
BLANK6 = ["......"] * 8
VLINE = "..#..."    # 0x20
HLINE = "######"    # 0xFC
HLEFT = "###..."    # 0xE0 -- up to and including the vertical column
HRIGHT = "..####"   # 0x3C -- from the vertical column rightwards

GRAPH = {
    0x60: [                       # diamond
        "......",
        "......",
        "..#...",
        ".###..",
        "..#...",
        "......",
        "......",
        "......",
    ],
    0x61: [                       # checkerboard
        "#.#.#.",
        ".#.#.#",
        "#.#.#.",
        ".#.#.#",
        "#.#.#.",
        ".#.#.#",
        "#.#.#.",
        ".#.#.#",
    ],
    0x66: [                       # degree sign
        "..##..",
        ".#..#.",
        ".#..#.",
        "..##..",
        "......",
        "......",
        "......",
        "......",
    ],
    0x67: [                       # plus/minus
        "..#...",
        ".####.",
        "..#...",
        "......",
        ".####.",
        "......",
        "......",
        "......",
    ],
    0x6A: [VLINE, VLINE, VLINE, HLEFT, *BLANK6[4:]],                     # lower-right
    0x6B: [*BLANK6[:3], HLEFT, VLINE, VLINE, VLINE, VLINE],              # upper-right
    0x6C: [*BLANK6[:3], HRIGHT, VLINE, VLINE, VLINE, VLINE],             # upper-left
    0x6D: [VLINE, VLINE, VLINE, HRIGHT, *BLANK6[4:]],                    # lower-left
    0x6E: [VLINE, VLINE, VLINE, HLINE, VLINE, VLINE, VLINE, VLINE],      # crossing
    0x6F: [HLINE, *BLANK6[1:]],                                          # scan 1
    0x70: [*BLANK6[:2], HLINE, *BLANK6[3:]],                             # scan 3
    0x71: [*BLANK6[:3], HLINE, *BLANK6[4:]],                             # scan 5
    0x72: [*BLANK6[:5], HLINE, *BLANK6[6:]],                             # scan 7
    0x73: [*BLANK6[:7], HLINE],                                          # scan 9
    0x74: [VLINE, VLINE, VLINE, HRIGHT, VLINE, VLINE, VLINE, VLINE],     # left tee
    0x75: [VLINE, VLINE, VLINE, HLEFT, VLINE, VLINE, VLINE, VLINE],      # right tee
    0x76: [VLINE, VLINE, VLINE, HLINE, *BLANK6[4:]],                     # bottom tee
    0x77: [*BLANK6[:3], HLINE, VLINE, VLINE, VLINE, VLINE],              # top tee
    0x78: [VLINE] * 8,                                                   # vertical
    0x7E: [                       # centred dot
        "......",
        "......",
        "......",
        "..##..",
        "..##..",
        "......",
        "......",
        "......",
    ],
}


def row_byte(s):
    v = 0
    for i, c in enumerate(s[:8]):
        if c == "#":
            v |= 0x80 >> i
    return v


def emit_table(name, lo, hi, source, default):
    n = hi - lo + 1
    print("static const u8 %s[%d][8] = {" % (name, n))
    for code in range(lo, hi + 1):
        glyph = source(code)
        if glyph is None:
            glyph = default
        bytes_ = ", ".join("0x%02X" % row_byte(r) for r in glyph)
        ch = chr(code) if 0x20 <= code <= 0x7E else "?"
        label = ch if ch.strip() else "SP"
        print("    { %s },  /* 0x%02X %s */" % (bytes_, code, label))
    print("};")
    print()


def main():
    print("/* font_graph_data.h -- GENERATED by tools/genfont.py; do not edit by hand. */")
    print("/* DEC special graphics on a 6-px cell (bits 7..2), bit 7 leftmost. */")
    print()
    emit_table("FONT_GRAPH", 0x5F, 0x7E, lambda c: GRAPH.get(c), BLANK6)


if __name__ == "__main__":
    main()
