#!/usr/bin/env python3
"""
romfont.py -- extract the 6x8 terminal font from a Timex Terminal TT3000 ROM.

Run:  python3 tools/romfont.py --rom ~/TT3000/TT3000.rom > src/font_ascii_data.h

The ROM holds 96 glyphs of 8 bytes at offset 0x0A27, covering 0x20-0x7F. Each
glyph's 6-pixel cell sits in bits 6..1, so we shift left by one: the cell then
occupies bits 7..2, bit 7 is the leftmost pixel (matching the rest of the
renderer), and every packing shift in render.c becomes a constant.

Only 0x20-0x7E is emitted, matching the shape FONT_ASCII already had.

The generated header is committed so CI and third parties can build without the
ROM, which is not redistributable.
"""
import argparse
import os
import sys

FONT_OFFSET = 0x0A27
FIRST_CODE = 0x20
LAST_CODE = 0x7E
GLYPH_BYTES = 8
COUNT = LAST_CODE - FIRST_CODE + 1


def read_rom(path):
    with open(path, "rb") as f:
        data = f.read()
    need = FONT_OFFSET + COUNT * GLYPH_BYTES
    if len(data) < need:
        sys.exit("ROM too short: %s is %d bytes, need at least %d" % (path, len(data), need))
    return data


def glyph(data, code):
    off = FONT_OFFSET + (code - FIRST_CODE) * GLYPH_BYTES
    return [(data[off + i] << 1) & 0xFF for i in range(GLYPH_BYTES)]


def check_pitch(data):
    """A glyph lighting bits 1..0 would collide with its right neighbour."""
    for code in range(FIRST_CODE, LAST_CODE + 1):
        if any(b & 0x03 for b in glyph(data, code)):
            sys.exit("glyph 0x%02X exceeds the 6-pixel cell (bits 1..0 set)" % code)


def emit(data):
    print("/* font_ascii_data.h -- GENERATED by tools/romfont.py; do not edit by hand. */")
    print("/* 6x8 glyphs from the Timex Terminal TT3000 ROM; cell in bits 7..2. */")
    print()
    print("static const u8 FONT_ASCII[%d][8] = {" % COUNT)
    for code in range(FIRST_CODE, LAST_CODE + 1):
        row = ", ".join("0x%02X" % b for b in glyph(data, code))
        label = "SP" if code == 0x20 else chr(code)
        print("    { %s },  /* 0x%02X %s */" % (row, code, label))
    print("};")


def main():
    ap = argparse.ArgumentParser(description="Extract the TT3000 6x8 font as C data.")
    ap.add_argument("--rom", default=os.environ.get("ROMFONT"),
                    help="path to the TT3000 ROM image (or set ROMFONT)")
    args = ap.parse_args()
    if not args.rom:
        sys.exit("no ROM given: pass --rom PATH or set ROMFONT")

    data = read_rom(args.rom)
    check_pitch(data)
    emit(data)


if __name__ == "__main__":
    main()
